
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    env OTEL_RESOURCE_ATTRIBUTES;
    # user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      include /etc/nginx/conf.d/*.conf;
      server {
        listen       8765;
        server_name  localhost;
        location / {
          root   /usr/share/nginx/html; #Change this line
          index  index.html index.htm;
        }

        location /api/customer/ {
          proxy_pass http://customers.demo.svc.cluster.local:8282/api/customer/;
        }
        location /api/vendor/ {
          proxy_pass http://compliance.demo.svc.cluster.local:8090/api/vendor/;
        }

        location /seznam {
          proxy_pass http://www.seznam.cz/;
        }
      }

    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        test: testval
      labels:
        app: nginx
        appdApp: MD-Hybrid-App
        otel: appd
        language: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1
        ports:
        - containerPort: 8765
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 100Mi
        env:
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: >-
            k8s.pod.ip=$(K8S_POD_IP),k8s.pod.name=$(K8S_POD_NAME),k8s.namespace.name=$(K8S_NAMESPACE_NAME),k8s.container.name=nginx
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8765
    protocol: TCP
    targetPort: 8765
  selector:
    app: nginx